### ISSUE TITLE
Safety of `AsciiPointer::from_slice_with_nul`

### ISSUE THREAD

**Issue by Za-michaelm** [ralfbiedert/interoptopus#126]
Hi, thanks for the library.

I made a silly mistake by implementing the following helper function:
```rust
fn to_ascii_pointer(string: &str) -> AsciiPointer {
    AsciiPointer::from_slice_with_nul(&format!("{string}\0").into_bytes()).unwrap()
}
```
Only to realize, late into testing, that it produces an `AsciiPointer` that points to freed memory.

Ideally, this kind of code should result in a compilation error.

**Comment by ralfbiedert** [comment]
Oh wow, this is a bad bug, thanks for pointing that out. I somehow missed to add the `<'a>` to the constructor function. It should read instead (on latest master):

```rust
pub fn from_slice_with_nul(cstr_with_nul: &'a [u8]) -> Result<CStrPointer<'a>, Error>
```

**Comment by Za-michaelm** [comment]
Thanks for the quick fix. I'm new to Rust, but isn't there a similar issue here?

https://github.com/ralfbiedert/interoptopus/blob/1c6cf0e86342e75afd6aa6594e0de708a89ec044/crates/core/src/patterns/slice.rs#L77-L83

**Comment by ralfbiedert** [comment]
>  I'm new to Rust, but isn't there a similar issue here?

No, because the `slice` parameter captures the `'a` lifetime (and `Self` has `'a` implicitly encoded through the `impl<'a, T> FFISlice<'a, T> {}` block surrounding that method). You can check this yourself, this won't work:

```rust
    fn to_vec(data: &[u8]) -> FFISlice<u8> {
        let v = data.to_vec();
        FFISlice::from_slice(v.as_slice())
    }
```

The first example you posted failed because in the previous ` pub fn from_slice_with_nul(cstr_with_nul: &[u8]) -> Result<Self, Error> {}` I forgot to mention `'a` in the parameter, which means Rust secretly introduced a fresh lifetime parameter `'b` instead, and was fine us pretending we could summon an  `AsciiPointer <'a>` seemingly out of thin air.

Once you have the correct `'a` in your input parameter (inside a block where `'a` is already tied to the struct), whether you then return `SomeStruct<'a>` or `Self` is just style (and yes, right now that style is a bit inconsistent).

**Comment by Za-michaelm** [comment]
> The first example you posted failed because in the previous ` pub fn from_slice_with_nul(cstr_with_nul: &[u8]) -> Result<Self, Error> {}` I forgot to mention `'a` in the parameter

That makes sense, but you also changed the return type in `from_cstr`, while `from_slice` looks similar to the variant before the change. Or was that one just a cosmetic fix? Sorry for the rookie lifetime questions :)

**Comment by ralfbiedert** [comment]
> Or was that one just a cosmetic fix?

Yes, that's what I meant about the style being inconsistent.
