### ISSUE TITLE
AsciiPointer is UTF8Pointer?

### ISSUE THREAD

**Issue by seaeagle1** [ralfbiedert/interoptopus#50]
To my pleasant surprise, I discovered that the AsciiPointer pattern plainly uses Rust CString, which is UTF-8 instead of ASCII. This is not an issue when transferring strings _into_ Rust, as ASCII is a subset of UTF-8, so Rust will happily handle both. However, it might surprise users when accepting strings _from_ Rust, when the Rust code accidentally outputs unicode characters (there's currently no check on this).

There seem to be two solutions to me: either perform a check in the Rust-implementation of AsciiPointer to make sure the string actually is ASCII, or, for me preferable, just support the unicode. For C both are null-terminated byte-strings anyway, so it just needs a clear warning sign for developers. For C# I've made a few small changes to the backend to explicitly marshal strings as UTF-8 which seems to work quite nicely (see https://github.com/seaeagle1/interoptopus/tree/utf8 ). I don't know much Python, but I'm sure it's also able to handle unicode strings.

**Comment by ralfbiedert** [comment]
> That's another option, but seems a lot of duplication for relatively little gain, since you can use an UTF8Pointer perfectly fine for ASCII as well, as long as you write the additional check if it's within the ASCII range yourself.

I agree on the Rust side, but I'm concerned about the FFI side. 

If we only had `UTF8Pointer` that means every backend and every language will have to support that. Since UTF-8 can contain `0x0`, that would mean these backends couldn't "type-safely" receive strings anymore from Rust. 

In other words, if you wrote a Rusty `fn f() -> UTF8Pointer`, in a hypothetical X-Lang that doesn't have native UTF-8 support you couldn't easily generate `f() -> String` anymore, as now the implicit contract is that Rust would either have to filter its strings, or 'X-Lang' might receive strings cut short (at an inner `0x0`).

**Comment by FeldrinH** [comment]
Maybe I'm misunderstanding something, but it seems to me that AsciiPointer is in practice just a 0x0 terminated u8 slice, not strictly ASCII, UTF-8 or any other encoding. If that is the case then calling it AsciiPointer seems misleading and will probably lead to users making dangerous assumptions.

**Comment by ralfbiedert** [comment]
> just a 0x0 terminated u8 slice, not strictly ASCII, UTF-8 or any other encoding

Yes, technically it's a `&CStr` equivalent. It's called `ASCIIPointer` as it was mostly used on incoming calls to signal that callers should only provide ASCII data. 

You are right from an outgoing perspective a Rust user might provide non-ASCII data which 3rd party languages might see, and after reviewing this thread I think there was some confusion on my side due to the title ('AsciiPointer is UTF8Pointer'). There's probably two ways forward:

- rename the struct 
- add Rust checks the data only contains ASCII when constructing 

If renamed, we might want to add more stringy types.
